$('#formContact').validate({
    rules:{
        email:{
            required:true,
            email:true
        },
        subject:{
            required:true
        },
        message:{
            required:true
        }
    }
})